name: CI/CD
on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{secrets.HEROKU_APP}} ${{secrets.HEROKU_API_KEY}}
  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/dev'
    steps:
      - run: echo 'Test Stage'
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo 'Deploy Stage'
      - run: apt-get update -qy
      - run: apt-get install -y ruby-dev
      - run: gem intsall dpl
      - run: dpl --provider=heroku --app=${{secrets.HEROKU_APP}} --api-key=${{secrets.HEROKU_API_KEY}}