name: CI/CD
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{secrets.HEROKU_APP}} ${{secrets.HEROKU_API_KEY}}
  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/dev'
    steps:
      - run: echo '  Stage'
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: 'olavao@uia.no'
