name: CI/CD
on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo $HEROKU_APP & $HEROKU_API_KEY
  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/dev'
    steps:
      - run: echo 'Test Stage'
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo 'Deploy Stage'